version: '2'

services:
  myapp:
    stdin_open: true
    image: 'bitnami/java-play:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8888:8888'
      - '9000:9000'
    volumes:
      - .:/app
